#!/usr/bin/env python3
"""Generate the deterministic IEC 61966-2-1 lighting transfer tables."""

from __future__ import annotations

import argparse
import math
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src/client/lighting_lut.inc"


def round_half_up(value: float) -> int:
    return math.floor(value + 0.5)


def srgb8_to_linear_q16(value: int) -> int:
    encoded = value / 255.0
    linear = encoded / 12.92 if encoded <= 0.04045 else ((encoded + 0.055) / 1.055) ** 2.4
    return round_half_up(linear * 65535.0)


def linear_q16_to_srgb8(value: int) -> int:
    linear = value / 65535.0
    encoded = 12.92 * linear if linear <= 0.0031308 else 1.055 * linear ** (1.0 / 2.4) - 0.055
    return min(255, max(0, round_half_up(encoded * 255.0)))


def render_values(values: list[int], width: int = 16) -> str:
    lines = []
    for offset in range(0, len(values), width):
        lines.append("    " + ", ".join(str(value) for value in values[offset : offset + width]) + ",\n")
    return "".join(lines)


def render() -> str:
    forward = [srgb8_to_linear_q16(value) for value in range(256)]
    inverse = [linear_q16_to_srgb8(value) for value in range(65536)]
    return (
        "/* Generated by client/tools/generate_lighting_lut.py. Do not edit. */\n"
        "static const uint16_t lighting_srgb8_to_linear_q16_lut[256] = {\n"
        + render_values(forward)
        + "};\n\n"
        "static const uint8_t lighting_linear_q16_to_srgb8_lut[65536] = {\n"
        + render_values(inverse)
        + "};\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    try:
        actual = OUTPUT.read_text(encoding="utf-8")
    except FileNotFoundError:
        actual = None
    if actual == expected:
        return 0
    if args.check:
        print(f"out of date: {OUTPUT}")
        return 1
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
