#!/usr/bin/env python3
"""Generate classic game protocol bindings from the canonical command schema."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


SYMBOL_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")
WIRE_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")
DIRECTIONS = ("client_to_server", "server_to_client")


def reject_duplicate_keys(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def load_schema(path: Path) -> dict[str, object]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=reject_duplicate_keys)
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
        raise ValueError(f"cannot load {path}: {exc}") from exc

    if not isinstance(data, dict):
        raise ValueError("schema root must be an object")
    if set(data) != {"schema_version", "protocol_version", "item_name_size", *DIRECTIONS}:
        raise ValueError("schema root has missing or unsupported keys")
    if data["schema_version"] != 1:
        raise ValueError("unsupported schema_version")
    protocol_version = data["protocol_version"]
    if isinstance(protocol_version, bool) or not isinstance(protocol_version, int):
        raise ValueError("protocol_version must be an integer")
    if protocol_version <= 0 or protocol_version > 0xFFFFFFFF:
        raise ValueError("protocol_version is outside uint32 range")
    item_name_size = data["item_name_size"]
    if isinstance(item_name_size, bool) or not isinstance(item_name_size, int):
        raise ValueError("item_name_size must be an integer")
    if item_name_size <= 1 or item_name_size > 0xFFFFFFFF:
        raise ValueError("item_name_size is outside the supported range")

    for direction in DIRECTIONS:
        commands = data[direction]
        if not isinstance(commands, list) or not commands:
            raise ValueError(f"{direction} must be a nonempty array")
        if len(commands) > 256:
            raise ValueError(f"{direction} exceeds the uint8 command space")

        seen_symbols: set[str] = set()
        seen_names: set[str] = set()
        for expected_id, command in enumerate(commands):
            if not isinstance(command, dict) or set(command) != {"id", "symbol", "wire_name"}:
                raise ValueError(f"{direction}[{expected_id}] has an invalid shape")

            command_id = command["id"]
            symbol = command["symbol"]
            wire_name = command["wire_name"]
            if isinstance(command_id, bool) or command_id != expected_id:
                raise ValueError(
                    f"{direction}[{expected_id}].id must be the contiguous value {expected_id}"
                )
            if not isinstance(symbol, str) or not SYMBOL_RE.fullmatch(symbol):
                raise ValueError(f"{direction}[{expected_id}].symbol is invalid")
            if not isinstance(wire_name, str) or not WIRE_NAME_RE.fullmatch(wire_name):
                raise ValueError(f"{direction}[{expected_id}].wire_name is invalid")
            if symbol in seen_symbols:
                raise ValueError(f"duplicate {direction} symbol: {symbol}")
            if wire_name in seen_names:
                raise ValueError(f"duplicate {direction} wire_name: {wire_name}")
            seen_symbols.add(symbol)
            seen_names.add(wire_name)

    return data


def generated_banner(comment: str) -> str:
    return (
        f"{comment} Generated by tools/generate.py from "
        f"schema/game-commands.json.\n"
        f"{comment} Do not edit by hand.\n"
    )


def render_header(schema: dict[str, object]) -> str:
    lines = [
        generated_banner("/*").replace("\n", " */\n", 2),
        "#ifndef ATRINIK_PROTOCOL_GAME_COMMANDS_H\n",
        "#define ATRINIK_PROTOCOL_GAME_COMMANDS_H\n\n",
        f"#define ATRINIK_PROTOCOL_VERSION {schema['protocol_version']}U\n",
        "#define SOCKET_VERSION ATRINIK_PROTOCOL_VERSION\n",
        f"#define ATRINIK_PROTOCOL_ITEM_NAME_SIZE {schema['item_name_size']}U\n\n",
        "typedef enum atrinik_client_to_server_command {\n",
    ]
    for command in schema["client_to_server"]:
        lines.append(f"    SERVER_CMD_{command['symbol']} = {command['id']},\n")
    lines.extend(
        [
            f"    SERVER_CMD_NROF = {len(schema['client_to_server'])}\n",
            "} atrinik_client_to_server_command_t;\n\n",
            "/* Stable diagnostic names for client-to-server commands. */\n",
        ]
    )
    for command in schema["client_to_server"]:
        lines.append(f"#define SERVER_CMD_NAME_{command['symbol']} \"{command['wire_name']}\"\n")
    lines.extend(
        [
            "\n",
            "typedef enum atrinik_server_to_client_command {\n",
        ]
    )
    for command in schema["server_to_client"]:
        lines.append(f"    CLIENT_CMD_{command['symbol']} = {command['id']},\n")
    lines.extend(
        [
            f"    CLIENT_CMD_NROF = {len(schema['server_to_client'])}\n",
            "} atrinik_server_to_client_command_t;\n\n",
            "/* Stable diagnostic names for server-to-client commands. */\n",
        ]
    )
    for command in schema["server_to_client"]:
        lines.append(f"#define CLIENT_CMD_NAME_{command['symbol']} \"{command['wire_name']}\"\n")
    lines.extend(
        [
            "\n",
            "#endif\n",
        ]
    )
    return "".join(lines)


def render_registry(schema: dict[str, object]) -> str:
    lines = [
        "/* Generated by tools/generate.py from\n",
        " * schema/game-commands.json. Do not edit by hand. */\n\n",
        "#ifndef ATRINIK_CLIENT_TO_SERVER_COMMAND\n",
        "#define ATRINIK_CLIENT_TO_SERVER_COMMAND(_id, _symbol, _name)\n",
        "#define ATRINIK_CLIENT_TO_SERVER_COMMAND_WAS_UNDEFINED\n",
        "#endif\n\n",
        "#ifndef ATRINIK_SERVER_TO_CLIENT_COMMAND\n",
        "#define ATRINIK_SERVER_TO_CLIENT_COMMAND(_id, _symbol, _name)\n",
        "#define ATRINIK_SERVER_TO_CLIENT_COMMAND_WAS_UNDEFINED\n",
        "#endif\n\n",
    ]
    for command in schema["client_to_server"]:
        lines.append(
            f"ATRINIK_CLIENT_TO_SERVER_COMMAND({command['id']}, {command['symbol']}, "
            f"\"{command['wire_name']}\")\n"
        )
    lines.append("\n")
    for command in schema["server_to_client"]:
        lines.append(
            f"ATRINIK_SERVER_TO_CLIENT_COMMAND({command['id']}, {command['symbol']}, "
            f"\"{command['wire_name']}\")\n"
        )
    lines.extend(
        [
            "\n#ifdef ATRINIK_CLIENT_TO_SERVER_COMMAND_WAS_UNDEFINED\n",
            "#undef ATRINIK_CLIENT_TO_SERVER_COMMAND_WAS_UNDEFINED\n",
            "#undef ATRINIK_CLIENT_TO_SERVER_COMMAND\n",
            "#endif\n\n",
            "#ifdef ATRINIK_SERVER_TO_CLIENT_COMMAND_WAS_UNDEFINED\n",
            "#undef ATRINIK_SERVER_TO_CLIENT_COMMAND_WAS_UNDEFINED\n",
            "#undef ATRINIK_SERVER_TO_CLIENT_COMMAND\n",
            "#endif\n",
        ]
    )
    return "".join(lines)


def render_python(schema: dict[str, object]) -> str:
    lines = [
        generated_banner("#"),
        "from enum import IntEnum\n\n",
        f"PROTOCOL_VERSION = {schema['protocol_version']}\n\n\n",
        f"ITEM_NAME_SIZE = {schema['item_name_size']}\n\n\n",
        "class ClientToServerCommand(IntEnum):\n",
    ]
    for command in schema["client_to_server"]:
        lines.append(f"    {command['symbol']} = {command['id']}\n")
    lines.extend(["\n\nclass ServerToClientCommand(IntEnum):\n"])
    for command in schema["server_to_client"]:
        lines.append(f"    {command['symbol']} = {command['id']}\n")
    return "".join(lines)


def expected_outputs(root: Path, schema: dict[str, object]) -> dict[Path, str]:
    return {
        root / "generated/c/include/atrinik/protocol/game_commands.h": render_header(schema),
        root / "generated/c/include/atrinik/protocol/game_commands.def": render_registry(schema),
        root / "generated/python/atrinik_protocol/game.py": render_python(schema),
    }


def update_outputs(outputs: dict[Path, str], check: bool) -> bool:
    current = True
    for path, expected in outputs.items():
        try:
            actual = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            actual = None
        if actual == expected:
            continue
        current = False
        if check:
            print(f"out of date: {path}", file=sys.stderr)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")
    return current


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="protocol repository root",
    )
    args = parser.parse_args()
    root = args.root.resolve()
    try:
        schema = load_schema(root / "schema/game-commands.json")
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0 if update_outputs(expected_outputs(root, schema), args.check) else 1


if __name__ == "__main__":
    raise SystemExit(main())
